# Site settings
title: Oluwaseun Omoyajowo
email: omoyajowo2015@gmail.com
description: Full Stack Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
enable_retina: false
nav_list:
  Home : ['Home', '/']
  Blog : ['Blog', '/blog']
  Resume : ['Resume', '/resume/Resume.pdf']  
  Contact : ['Contact', '/contact']
footer_links:
    Writer: ['FlickzCode 2017', '/about']


# Build settings
markdown: kramdown
